# Generated by Django 5.0.4 on 2024-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskManager',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(max_length=122)),
                ('status', models.BooleanField(max_length=122)),
            ],
        ),
    ]
