# Generated by Django 5.0.4 on 2024-05-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='priority',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='status',
            field=models.BooleanField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=200),
        ),
    ]
