# Generated by Django 5.0.4 on 2024-05-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0002_alter_taskmanager_name_alter_taskmanager_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=200),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='status',
            field=models.BooleanField(max_length=200),
        ),
    ]
